In [1]:
import numpy as np

In [2]:
x = np.random.normal(0, 1, size=100)
x

array([ 0.29304927, -1.18936878, -1.12318153,  1.04120794, -0.73304912,
        0.70638768, -0.96288462,  1.35216258,  0.63745332, -2.02502117,
        0.71886656,  1.2100398 ,  2.21427214, -0.82449124, -0.53479342,
       -0.18649883,  0.83857701, -0.37295444, -0.30389255,  0.02477908,
        0.84277489,  0.48970575, -1.12182566, -0.02269588, -0.23150018,
       -0.29640254, -0.52277358, -0.00444394, -0.34288673,  0.56934159,
        0.16003914,  1.81514425, -0.34514937,  0.36772769,  0.57851532,
       -0.18706243, -1.16599831, -0.15654546, -0.43588945, -1.0169147 ,
        0.13539292,  0.26824712, -1.07437751, -0.43162162,  0.05375219,
       -1.2094985 , -0.23678867,  0.26965767, -1.00072949, -0.34278251,
        0.3865148 , -0.00939369, -1.24601553,  1.99488415,  0.59229592,
       -0.01219198,  0.05599043, -0.10630827, -0.16069453, -0.29536259,
        0.76984213,  1.41859066, -0.37828917,  1.60549283,  0.77230356,
       -1.27597966,  1.62130575, -0.12210764, -0.37576929,  1.11

In [3]:
am = np.argmin(x)
am

9

#### 排序

In [4]:
x = np.arange(16)
np.random.shuffle(x)
x

array([11,  8,  3,  4, 13, 10, 14,  0,  1,  9,  6,  2, 15, 12,  7,  5])

In [5]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [6]:
A = x.reshape(4,4)
A

array([[11,  8,  3,  4],
       [13, 10, 14,  0],
       [ 1,  9,  6,  2],
       [15, 12,  7,  5]])

In [7]:
np.sort(A)

array([[ 3,  4,  8, 11],
       [ 0, 10, 13, 14],
       [ 1,  2,  6,  9],
       [ 5,  7, 12, 15]])

In [8]:
A

array([[11,  8,  3,  4],
       [13, 10, 14,  0],
       [ 1,  9,  6,  2],
       [15, 12,  7,  5]])

In [9]:
np.sort(A, axis=0)

array([[ 1,  8,  3,  0],
       [11,  9,  6,  2],
       [13, 10,  7,  4],
       [15, 12, 14,  5]])

In [10]:
x

array([11,  8,  3,  4, 13, 10, 14,  0,  1,  9,  6,  2, 15, 12,  7,  5])

In [11]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
np.argsort(x)

array([ 7,  8, 11,  2,  3, 15, 10, 14,  1,  9,  5,  0, 13,  4,  6, 12])

In [14]:
np.partition(x, 5)

array([ 1,  0,  3,  4,  2,  5, 14,  8, 10,  9,  6, 13, 15, 12,  7, 11])

In [17]:
A = np.arange(16).reshape(4, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
x = np.arange(16)
[x[3], x[5], x[8]]

[3, 5, 8]

In [19]:
(x[3], x[6], x[8])

(3, 6, 8)

In [20]:
ind = [3, 5, 8]
x[ind]

array([3, 5, 8])

In [26]:
ind = np.array([[0,3],[1,2]])
x[ind]

array([[0, 3],
       [1, 2]])

In [29]:
row = np.array([0, 2])
col = np.array([0, 2])
# 取(0,0), (2,2)两个点
A[row, col]

array([ 0, 10])

In [30]:
col = [True, False, True, True]
A[:, col]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15]])

In [32]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [33]:
np.sum(x < 4)

4

In [34]:
np.any(x < 5)

True

In [35]:
np.any(x < 0)

False

In [36]:
np.all(x < 5), np.all(x >= 0)

(False, True)

In [37]:
np.sum((x > 3) & (x < 10))

6

In [41]:
np.sum( ~(x == 0))

15

In [42]:
x[ x % 2 == 0 ]

array([ 0,  2,  4,  6,  8, 10, 12, 14])