In [4]:
import numpy as np

In [8]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
X.ndim
x.ndim

1

In [12]:
X.shape

(3, 5)

In [14]:
X.size

15

In [16]:
X[1, 2]

7

In [18]:
x[4::-2]

array([4, 2, 0])

用列表方式访问X[切片x, 切片y]

In [19]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [20]:
X[1, :]

array([5, 6, 7, 8, 9])

In [21]:
subX = X
subX[0, 0] = 100
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [23]:
Y = X[1:, 2:].copy()
Y

array([[ 7,  8,  9],
       [12, 13, 14]])

reshape

In [26]:
X2 = x.reshape(2, 5).copy()
X2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
x.shape

(10,)

In [28]:
X2.shape

(2, 5)

In [29]:
x.reshape(10, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

### 合并分割

In [42]:
x = np.array([1,2,3])
y = np.array([3,2,1])
z = np.array([666, 666, 666])

In [43]:
np.concatenate([x, y, x])

array([1, 2, 3, 3, 2, 1, 1, 2, 3])

In [44]:
A = np.array([x, y])
A

array([[1, 2, 3],
       [3, 2, 1]])

In [45]:
np.concatenate([A, A])

array([[1, 2, 3],
       [3, 2, 1],
       [1, 2, 3],
       [3, 2, 1]])

In [46]:
np.concatenate([A, A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [3, 2, 1, 3, 2, 1]])

In [49]:
A2 = np.concatenate([A, z.reshape(1, -1)])
A2

array([[  1,   2,   3],
       [  3,   2,   1],
       [666, 666, 666]])

In [50]:
np.vstack([A, z])

array([[  1,   2,   3],
       [  3,   2,   1],
       [666, 666, 666]])

In [51]:
B = np.full((2,2), 100)
B

array([[100, 100],
       [100, 100]])

In [54]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  3,   2,   1, 100, 100]])

In [56]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
x1, x2, x3 = np.split(x, [3, 7])

In [58]:
x1

array([0, 1, 2])

In [59]:
x2

array([3, 4, 5, 6])

In [60]:
x3

array([7, 8, 9])

In [62]:
A = np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [63]:
np.split(A, [2], axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [67]:
X, y = np.hsplit(A, [-1])

In [65]:
np.vsplit(A, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [68]:
y = y.reshape(-1)
y

array([ 3,  7, 11, 15])