In [1]:
import numpy as np

n = 10
L = [i for i in range(n)]

In [2]:
%%time
A = [2*e for e in L]


CPU times: user 6 µs, sys: 1 µs, total: 7 µs
Wall time: 9.06 µs


In [3]:
%%time
A = np.array(L)
A * 2

CPU times: user 81 µs, sys: 15 µs, total: 96 µs
Wall time: 57.7 µs


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
A ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
np.cos(A)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [6]:
A = np.arange(4).reshape(2,2)
B = np.full((2,2), 10)
B

array([[10, 10],
       [10, 10]])

In [7]:
A * B

array([[ 0, 10],
       [20, 30]])

In [9]:
(A*10).dot(B)

array([[100, 100],
       [500, 500]])

In [10]:
A.T

array([[0, 2],
       [1, 3]])

In [17]:
x = np.arange(2)
x = x + 1
x

array([1, 2])

In [18]:
A

array([[0, 1],
       [2, 3]])

In [19]:
A + x

array([[1, 3],
       [3, 5]])

In [27]:
np.vstack([x] * A.shape[0])

array([[1, 2],
       [1, 2]])

In [28]:
A.dot(x)

array([2, 8])

In [29]:
x.dot(A)

array([4, 7])

In [30]:
Av = np.linalg.inv(A)
Av

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [31]:
Av.dot(A)

array([[1., 0.],
       [0., 1.]])

In [34]:
pA = np.arange(16).reshape(2,8)
aPinv = np.linalg.pinv(pA)
aPinv

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -7.30583920e-18],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])