In [1]:
import numpy as np

In [2]:
x = np.random.randint(0, 100, 100)
x

array([33, 94, 86, 84, 10, 73, 95,  3, 68, 14, 49, 29, 14, 23, 43, 89, 40,
       86, 64, 86,  8, 71, 18, 52, 85, 73, 60, 20, 59, 29, 57, 48, 13, 31,
       61, 72, 18, 11, 92, 80, 54, 54, 36, 29, 70, 19, 56, 82, 96, 30, 88,
        4, 97, 69, 71, 85, 99, 42, 77, 63, 53, 77, 91, 55, 12, 99, 16, 18,
       41, 73, 10, 52, 77, 68, 53, 70, 51,  5, 11, 67, 69, 86, 22, 97, 81,
       89, 77, 91, 54, 66, 72, 28, 47, 63, 33, 84, 54, 76, 97, 25])

In [3]:
(x - np.min(x)) / (np.max(x) - np.min(x))

array([0.3125    , 0.94791667, 0.86458333, 0.84375   , 0.07291667,
       0.72916667, 0.95833333, 0.        , 0.67708333, 0.11458333,
       0.47916667, 0.27083333, 0.11458333, 0.20833333, 0.41666667,
       0.89583333, 0.38541667, 0.86458333, 0.63541667, 0.86458333,
       0.05208333, 0.70833333, 0.15625   , 0.51041667, 0.85416667,
       0.72916667, 0.59375   , 0.17708333, 0.58333333, 0.27083333,
       0.5625    , 0.46875   , 0.10416667, 0.29166667, 0.60416667,
       0.71875   , 0.15625   , 0.08333333, 0.92708333, 0.80208333,
       0.53125   , 0.53125   , 0.34375   , 0.27083333, 0.69791667,
       0.16666667, 0.55208333, 0.82291667, 0.96875   , 0.28125   ,
       0.88541667, 0.01041667, 0.97916667, 0.6875    , 0.70833333,
       0.85416667, 1.        , 0.40625   , 0.77083333, 0.625     ,
       0.52083333, 0.77083333, 0.91666667, 0.54166667, 0.09375   ,
       1.        , 0.13541667, 0.15625   , 0.39583333, 0.72916667,
       0.07291667, 0.51041667, 0.77083333, 0.67708333, 0.52083

In [6]:
y = np.array(x, dtype=float)

In [8]:
(y - np.mean(y)) / np.std(y)

array([-0.80784981,  1.36111315,  1.07665899,  1.00554545, -1.62565552,
        0.61442098,  1.39666992, -1.8745529 ,  0.43663713, -1.48342844,
       -0.23894149, -0.95007689, -1.48342844, -1.16341751, -0.45228211,
        1.1833293 , -0.55895242,  1.07665899,  0.29441005,  1.07665899,
       -1.69676906,  0.54330744, -1.34120136, -0.13227118,  1.04110222,
        0.61442098,  0.15218297, -1.27008782,  0.1166262 , -0.95007689,
        0.04551267, -0.27449826, -1.51898521, -0.87896335,  0.18773974,
        0.57886421, -1.34120136, -1.59009875,  1.28999961,  0.86331837,
       -0.06115764, -0.06115764, -0.7011795 , -0.95007689,  0.50775067,
       -1.30564459,  0.0099559 ,  0.93443191,  1.43222669, -0.91452012,
        1.14777253, -1.83899613,  1.46778346,  0.4721939 ,  0.54330744,
        1.04110222,  1.538897  , -0.48783888,  0.75664806,  0.25885328,
       -0.09671441,  0.75664806,  1.25444284, -0.02560087, -1.55454198,
        1.538897  , -1.4123149 , -1.34120136, -0.52339565,  0.61

In [10]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import numpy as np

iris_dataset = load_iris()
X = iris_dataset.data
y = iris_dataset.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666, shuffle=True)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)


StandardScaler()

In [12]:
scaler.mean_

array([5.83416667, 3.08666667, 3.70833333, 1.17      ])

In [13]:
scaler.scale_

array([0.81019502, 0.44327067, 1.76401924, 0.75317107])

In [14]:
scaler.transform(X_train)

array([[-0.90616043,  0.93246262, -1.30856471, -1.28788802],
       [-1.15301457, -0.19551636, -1.30856471, -1.28788802],
       [-0.16559799, -0.64670795,  0.22203084,  0.17260355],
       [ 0.45153738,  0.70686683,  0.95898425,  1.50032315],
       [-0.90616043, -1.32349533, -0.40154513, -0.09294037],
       [ 1.43895396,  0.25567524,  0.56216318,  0.30537551],
       [ 0.3281103 , -1.09789954,  1.0723617 ,  0.30537551],
       [ 2.1795164 , -0.19551636,  1.63924894,  1.23477923],
       [-0.78273335,  2.2860374 , -1.25187599, -1.42065998],
       [ 0.45153738, -2.00028272,  0.44878573,  0.43814747],
       [ 1.80923518, -0.42111215,  1.46918276,  0.83646335],
       [ 0.69839152,  0.25567524,  0.90229552,  1.50032315],
       [ 0.20468323,  0.70686683,  0.44878573,  0.57091943],
       [-0.78273335, -0.87230374,  0.10865339,  0.30537551],
       [-0.53587921,  1.38365421, -1.25187599, -1.28788802],
       [-0.65930628,  1.38365421, -1.25187599, -1.28788802],
       [-1.0295875 ,  0.